const config = {
  machineReadableClimateData: {
    "Annual Extremes rainfall/temperature (Jan-Dec)": {
      season: "Annual_Extremes_rainfalltemperature_Jan-Dec",
      metrics: {
        "Days with Precipitation Greater than 1 inch":
          "Days_with_Precipitation_Greater_than_1_inch",
        "Days with Precipitation Greater than 2 inches":
          "Days_with_Precipitation_Greater_than_2_inches",
        "Days with Precipitation Greater than 3 inches":
          "Days_with_Precipitation_Greater_than_3_inches",
        "Days with Precipitation Greater than 4 inches":
          "Days_with_Precipitation_Greater_than_4_inches",
        "Days with Maximum Temperature Below 0°F":
          "Days_with_Maximum_Temperature_Below_0F",
        "Days with Maximum Temperature Below 32°F":
          "Days_with_Maximum_Temperature_Below_32F",
        "Days with Maximum Temperature Above 90°F":
          "Days_with_Maximum_Temperature_Above_90F",
        "Days with Maximum Temperature Above 95°F":
          "Days_with_Maximum_Temperature_Above_95F",
        "Days with Maximum Temperature Above 100°F":
          "Days_with_Maximum_Temperature_Above_100F",
        "Days with Minimum Temperature Below 0°F":
          "Days_with_Minimum_Temperature_Below_0F",
        "Days with Minimum Temperature Below 32°F":
          "Days_with_Minimum_Temperature_Below_32F",
        "Days with Minimum Temperature Above 70°F":
          "Days_with_Minimum_Temperature_Above_70F",
        "Days with Minimum Temperature Above 75":
          "Days_with_Minimum_Temperature_Above_75",
        "Days with Minimum Temperature Above 80°F":
          "Days_with_Minimum_Temperature_Above_80F",
      },
    },
    "Annual Mean (Jan-Dec)": {
      season: "Annual_Mean_Jan-Dec",
      metrics: {
        "Cooling Degree Days": "Cooling_Degree_Days",
        "Heating Degree Days": "Heating_Degree_Days",
        "Total Precipitation": "Total_Precipitation",
        "Average Temperature": "Average_Temperature",
        "Average Minimum Temperature": "Average_Minimum_Temperature",
        "Average Maximum Temperature": "Average_Maximum_Temperature",
      },
    },
    "Spring Mean (Mar-May)": {
      season: "Spring_Mean_Mar-May",
      metrics: {
        "Cooling Degree Days": "Cooling_Degree_Days",
        "Heating Degree Days": "Heating_Degree_Days",
        "Total Precipitation": "Total_Precipitation",
        "Average Temperature": "Average_Temperature",
        "Average Minimum Temperature": "Average_Minimum_Temperature",
        "Average Maximum Temperature": "Average_Maximum_Temperature",
      },
    },
    "Summer Mean (Jun-Aug)": {
      season: "Summer_Mean_Jun-Aug",
      metrics: {
        "Cooling Degree Days": "Cooling_Degree_Days",
        "Heating Degree Days": "Heating_Degree_Days",
        "Total Precipitation": "Total_Precipitation",
        "Average Temperature": "Average_Temperature",
        "Average Minimum Temperature": "Average_Minimum_Temperature",
        "Average Maximum Temperature": "Average_Maximum_Temperature",
      },
    },
    "Fall Mean (Sep-Nov)": {
      season: "Fall_Mean_Sep-Nov",
      metrics: {
        "Cooling Degree Days": "Cooling_Degree_Days",
        "Heating Degree Days": "Heating_Degree_Days",
        "Total Precipitation": "Total_Precipitation",
        "Average Temperature": "Average_Temperature",
        "Average Minimum Temperature": "Average_Minimum_Temperature",
        "Average Maximum Temperature": "Average_Maximum_Temperature",
      },
    },
    "Winter Mean (Dec-Feb)": {
      season: "Winter_Mean_Dec-Feb",
      metrics: {
        "Cooling Degree Days": "Cooling_Degree_Days",
        "Heating Degree Days": "Heating_Degree_Days",
        "Total Precipitation": "Total_Precipitation",
        "Average Temperature": "Average_Temperature",
        "Average Minimum Temperature": "Average_Minimum_Temperature",
        "Average Maximum Temperature": "Average_Maximum_Temperature",
      },
    },
  },
  locationTypeMapping: {
    Alaska: "states",
    Alabama: "states",
    Arizona: "states",
    Arkansas: "states",
    California: "states",
    Colorado: "states",
    Connecticut: "states",
    Delaware: "states",
    Florida: "states",
    Georgia: "states",
    "Hawai'i": "states",
    Idaho: "states",
    Illinois: "states",
    Indiana: "states",
    Iowa: "states",
    Kansas: "states",
    Kentucky: "states",
    Louisiana: "states",
    Maine: "states",
    Maryland: "states",
    Massachusetts: "states",
    Michigan: "states",
    Minnesota: "states",
    Mississippi: "states",
    Missouri: "states",
    Montana: "states",
    Nebraska: "states",
    Nevada: "states",
    "New Hampshire": "states",
    "New Jersey": "states",
    "New Mexico": "states",
    "New York": "states",
    "North Carolina": "states",
    "North Dakota": "states",
    Ohio: "states",
    Oklahoma: "states",
    Oregon: "states",
    Pennsylvania: "states",
    "Puerto Rico": "states",
    "Rhode Island": "states",
    "South Carolina": "states",
    "South Dakota": "states",
    Tennessee: "states",
    Texas: "states",
    Utah: "states",
    Vermont: "states",
    Virginia: "states",
    "Virgin Islands": "states",
    Washington: "states",
    "West Virginia": "states",
    Wisconsin: "states",
    Wyoming: "states",
    "Contiguous United States": "CONUS",
    "Alaska ": "regions",
    "Hawai'i and US-Affiliated Pacific Islands": "regions",
    Midwest: "regions",
    "Northern Great Plains": "regions",
    "Northeast Great Plains": "regions",
    Northwest: "regions",
    Southeast: "regions",
    "Southern Great Plains": "regions",
    Southwest: "regions",
    "US Caribbean": "regions",
  },
  stateAbbreviations: {
    Alaska: "AK",
    Alabama: "AL",
    Arizona: "AZ",
    Arkansas: "AR",
    California: "CA",
    Colorado: "CO",
    Connecticut: "CT",
    Delaware: "DE",
    Florida: "FL",
    Georgia: "GA",
    "Hawai'i": "HI",
    Idaho: "ID",
    Illinois: "IL",
    Indiana: "IN",
    Iowa: "IA",
    Kansas: "KS",
    Kentucky: "KY",
    Louisiana: "LA",
    Maine: "ME",
    Maryland: "MD",
    Massachusetts: "MA",
    Michigan: "MI",
    Minnesota: "MN",
    Mississippi: "MS",
    Missouri: "MO",
    Montana: "MT",
    Nebraska: "NE",
    Nevada: "NV",
    "New Hampshire": "NH",
    "New Jersey": "NJ",
    "New Mexico": "NM",
    "New York": "NY",
    "North Carolina": "NC",
    "North Dakota": "ND",
    Ohio: "OH",
    Oklahoma: "OK",
    Oregon: "OR",
    Pennsylvania: "PA",
    "Puerto Rico": "PR",
    "Rhode Island": "RI",
    "South Carolina": "SC",
    "South Dakota": "SD",
    Tennessee: "TN",
    Texas: "TX",
    Utah: "UT",
    Vermont: "VT",
    Virginia: "VA",
    "Virgin Islands": "VI",
    Washington: "WA",
    "West Virginia": "WV",
    Wisconsin: "WI",
    Wyoming: "WY",
  },
  ncaRegionAbbreviations: {
    Alaska: "Alaska",
    Northeast: "Northeast",
    "Northern Rockies and Plains": "Northern Rockies And Plains",
    Northwest: "Northwest",
    "Ohio Valley": "Ohio Valley",
    South: "South",
    Southeast: "Southeast",
    Southwest: "Southwest",
    "Upper Midwest": "Upper Midwest",
    West: "West",
    "Hawai'i and US-Affiliated Pacific Islands": "Hawaii",
    "US Caribbean": "Us_Caribbean",
    "Contiguous United States": "contiguous_united_states",
  },
  metricToFileTypeMapping: {
    Days_with_Precipitation_Greater_than_1_inch: "prcp_1inch",
    Days_with_Precipitation_Greater_than_2_inches: "prcp_2inch",
    Days_with_Precipitation_Greater_than_3_inches: "prcp_3inch",
    Days_with_Precipitation_Greater_than_4_inches: "prcp_4inch",
    Days_with_Maximum_Temperature_Below_0F: "tmax_0F",
    Days_with_Maximum_Temperature_Below_32F: "tmax_32F",
    Days_with_Maximum_Temperature_Above_90F: "tmax_90F",
    Days_with_Maximum_Temperature_Above_95F: "tmax_95F",
    Days_with_Maximum_Temperature_Above_100F: "tmax_100F",
    Days_with_Minimum_Temperature_Below_0F: "tmin_0F",
    Days_with_Minimum_Temperature_Below_32F: "tmin_32F",
    Days_with_Minimum_Temperature_Above_70F: "tmin_70F",
    Days_with_Minimum_Temperature_Above_75: "tmin_75F",
    Days_with_Minimum_Temperature_Above_80F: "tmin_80F",
    Cooling_Degree_Days: "cdd",
    Heating_Degree_Days: "hdd",
    Total_Precipitation: "prcp_ann",
    Average_Temperature: "tmean_ann",
    Average_Minimum_Temperature: "tmin_ann",
    Average_Maximum_Temperature: "tmax_ann",
  },
};

export default config;
