const config = {
  dropdownOptionsList: [
    "Alaska",
    "Alabama",
    "Arizona",
    "Arkansas",
    "California",
    "Colorado",
    "Connecticut",
    "Delaware",
    "Florida",
    "Georgia",
    "Hawai'i",
    "Idaho",
    "Illinois",
    "Indiana",
    "Iowa",
    "Kansas",
    "Kentucky",
    "Louisiana",
    "Maine",
    "Maryland",
    "Massachusetts",
    "Michigan",
    "Minnesota",
    "Mississippi",
    "Missouri",
    "Montana",
    "Nebraska",
    "Nevada",
    "New Hampshire",
    "New Jersey",
    "New Mexico",
    "New York",
    "North Carolina",
    "North Dakota",
    "Ohio",
    "Oklahoma",
    "Oregon",
    "Pennsylvania",
    "Puerto Rico",
    "Rhode Island",
    "South Carolina",
    "South Dakota",
    "Tennessee",
    "Texas",
    "Utah",
    "Vermont",
    "Virginia",
    "Virgin Islands",
    "Washington",
    "West Virginia",
    "Wisconsin",
    "Wyoming",
    "Contiguous United States",
    "Alaska (NCA Region)",
    "Hawai'i and US-Affiliated Pacific Islands (NCA Region)",
    "Midwest (NCA Region)",
    "Northern Great Plains (NCA Region)",
    "Northeast Great Plains (NCA Region)",
    "Northwest (NCA Region)",
    "Southeast (NCA Region)",
    "Southern Great Plains (NCA Region)",
    "Southwest (NCA Region)",
    "US Caribbean (NCA Region)",
  ],
  climateDataHierarchy: {
    "Annual Extremes rainfall/temperature (Jan-Dec)": [
      "Days with Precipitation Greater than 1 inch",
      "Days with Precipitation Greater than 2 inches",
      "Days with Precipitation Greater than 3 inches",
      "Days with Precipitation Greater than 4 inches",
      "Days with Maximum Temperature Below 0°F",
      "Days with Maximum Temperature Below 32°F",
      "Days with Maximum Temperature Above 90°F",
      "Days with Maximum Temperature Above 95°F",
      "Days with Maximum Temperature Above 100°F",
      "Days with Minimum Temperature Below 0°F",
      "Days with Minimum Temperature Below 32°F",
      "Days with Minimum Temperature Above 70°F",
      "Days with Minimum Temperature Above 75",
      "Days with Minimum Temperature Above 80°F",
    ],
    "Annual Mean (Jan-Dec)": [
      "Cooling Degree Days",
      "Heating Degree Days",
      "Total Precipitation",
      "Average Temperature",
      "Average Minimum Temperature",
      "Average Maximum Temperature",
    ],
    "Spring Mean (Mar-May)": [
      "Cooling Degree Days",
      "Heating Degree Days",
      "Total Precipitation",
      "Average Temperature",
      "Average Minimum Temperature",
      "Average Maximum Temperature",
    ],
    "Summer Mean (Jun-Aug)": [
      "Cooling Degree Days",
      "Heating Degree Days",
      "Total Precipitation",
      "Average Temperature",
      "Average Minimum Temperature",
      "Average Maximum Temperature",
    ],
    "Fall Mean (Sep-Nov)": [
      "Cooling Degree Days",
      "Heating Degree Days",
      "Total Precipitation",
      "Average Temperature",
      "Average Minimum Temperature",
      "Average Maximum Temperature",
    ],
    "Winter Mean (Dec-Feb)": [
      "Cooling Degree Days",
      "Heating Degree Days",
      "Total Precipitation",
      "Average Temperature",
      "Average Minimum Temperature",
      "Average Maximum Temperature",
    ],
  },
};

export default config;
