const config = {
  stateAbbreviations: {
    Alaska: "AK",
    Alabama: "AL",
    Arizona: "AZ",
    Arkansas: "AR",
    California: "CA",
    Colorado: "CO",
    Connecticut: "CT",
    Delaware: "DE",
    Florida: "FL",
    Georgia: "GA",
    "Hawai'i": "HI",
    Idaho: "ID",
    Illinois: "IL",
    Indiana: "IN",
    Iowa: "IA",
    Kansas: "KS",
    Kentucky: "KY",
    Louisiana: "LA",
    Maine: "ME",
    Maryland: "MD",
    Massachusetts: "MA",
    Michigan: "MI",
    Minnesota: "MN",
    Mississippi: "MS",
    Missouri: "MO",
    Montana: "MT",
    Nebraska: "NE",
    Nevada: "NV",
    "New Hampshire": "NH",
    "New Jersey": "NJ",
    "New Mexico": "NM",
    "New York": "NY",
    "North Carolina": "NC",
    "North Dakota": "ND",
    Ohio: "OH",
    Oklahoma: "OK",
    Oregon: "OR",
    Pennsylvania: "PA",
    "Puerto Rico": "PR",
    "Rhode Island": "RI",
    "South Carolina": "SC",
    "South Dakota": "SD",
    Tennessee: "TN",
    Texas: "TX",
    Utah: "UT",
    Vermont: "VT",
    Virginia: "VA",
    "Virgin Islands": "VI",
    Washington: "WA",
    "West Virginia": "WV",
    Wisconsin: "WI",
    Wyoming: "WY",
  },
  ncaRegionAbbreviations: {
    Alaska: "Alaska",
    Northeast: "Northeast",
    "Northern Rockies and Plains": "Northern Rockies And Plains",
    Northwest: "Northwest",
    "Ohio Valley": "Ohio Valley",
    South: "South",
    Southeast: "Southeast",
    Southwest: "Southwest",
    "Upper Midwest": "Upper Midwest",
    West: "West",
    "Hawai'i and US-Affiliated Pacific Islands": "Hawaii",
    "US Caribbean": "Us_Caribbean",
    "Contiguous United States": "contiguous_united_states",
  },
  // States options for MegaMenu.jsx
  statesOptions: [
    {
      label: "Alabama",
      svg: "/svgs/states/Alabama.svg",
      value: "Alabama",
      type: "states",
      startDates: {
        threshold: "1900",
        temperature: "1895",
        precipitation: "1895",
      },
      endDates: {
        threshold: "2024",
        temperature: "2024",
        precipitation: "2024",
      },
    },
    {
      label: "Alaska",
      svg: "/svgs/states/Alaska.svg",
      value: "Alaska",
      type: "states",
      startDates: {
        threshold: "1930",
        temperature: "1925",
        precipitation: "1925",
      },
      endDates: {
        threshold: "2024",
        temperature: "2024",
        precipitation: "2024",
      },
    },
    {
      label: "Arizona",
      svg: "/svgs/states/Arizona.svg",
      value: "Arizona",
      type: "states",
      startDates: {
        threshold: "1930",
        temperature: "1895",
        precipitation: "1895",
      },
      endDates: {
        threshold: "2024",
        temperature: "2024",
        precipitation: "2024",
      },
    },
    {
      label: "Arkansas",
      svg: "/svgs/states/Arkansas.svg",
      value: "Arkansas",
      type: "states",
      startDates: {
        threshold: "1900",
        temperature: "1895",
        precipitation: "1895",
      },
      endDates: {
        threshold: "2024",
        temperature: "2024",
        precipitation: "2024",
      },
    },
    {
      label: "California",
      svg: "/svgs/states/California.svg",
      value: "California",
      type: "states",
      startDates: {
        threshold: "1930",
        temperature: "1895",
        precipitation: "1895",
      },
      endDates: {
        threshold: "2024",
        temperature: "2024",
        precipitation: "2024",
      },
    },
    {
      label: "Colorado",
      svg: "/svgs/states/Colorado.svg",
      value: "Colorado",
      type: "states",
      startDates: {
        threshold: "1900",
        temperature: "1895",
        precipitation: "1895",
      },
      endDates: {
        threshold: "2024",
        temperature: "2024",
        precipitation: "2024",
      },
    },
    {
      label: "Connecticut",
      svg: "/svgs/states/Connecticut.svg",
      value: "Connecticut",
      type: "states",
      startDates: {
        threshold: "1950",
        temperature: "1895",
        precipitation: "1895",
      },
      endDates: {
        threshold: "2024",
        temperature: "2024",
        precipitation: "2024",
      },
    },
    {
      label: "Delaware",
      svg: "/svgs/states/Delaware.svg",
      value: "Delaware",
      type: "states",
      startDates: {
        threshold: "1900",
        temperature: "1895",
        precipitation: "1895",
      },
      endDates: {
        threshold: "2024",
        temperature: "2024",
        precipitation: "2024",
      },
    },
    {
      label: "Florida",
      svg: "/svgs/states/Florida.svg",
      value: "Florida",
      type: "states",
      startDates: {
        threshold: "1900",
        temperature: "1895",
        precipitation: "1895",
      },
      endDates: {
        threshold: "2024",
        temperature: "2024",
        precipitation: "2024",
      },
    },
    {
      label: "Georgia",
      svg: "/svgs/states/Georgia.svg",
      value: "Georgia",
      type: "states",
      startDates: {
        threshold: "1900",
        temperature: "1895",
        precipitation: "1895",
      },
      endDates: {
        threshold: "2024",
        temperature: "2024",
        precipitation: "2024",
      },
    },
    {
      label: "Hawai'i",
      svg: "/svgs/states/Hawaii.svg",
      value: "Hawaii",
      type: "states",
      startDates: {
        threshold: "1950",
        temperature: "1895",
        precipitation: "1895",
      },
      endDates: {
        threshold: "2024",
        temperature: "2024",
        precipitation: "2024",
      },
    },
    {
      label: "Idaho",
      svg: "/svgs/states/Idaho.svg",
      value: "Idaho",
      type: "states",
      startDates: {
        threshold: "1900",
        temperature: "1895",
        precipitation: "1895",
      },
      endDates: {
        threshold: "2024",
        temperature: "2024",
        precipitation: "2024",
      },
    },
    {
      label: "Illinois",
      svg: "/svgs/states/Illinois.svg",
      value: "Illinois",
      type: "states",
      startDates: {
        threshold: "1900",
        temperature: "1895",
        precipitation: "1895",
      },
      endDates: {
        threshold: "2024",
        temperature: "2024",
        precipitation: "2024",
      },
    },
    {
      label: "Indiana",
      svg: "/svgs/states/Indiana.svg",
      value: "Indiana",
      type: "states",
      startDates: {
        threshold: "1900",
        temperature: "1895",
        precipitation: "1895",
      },
      endDates: {
        threshold: "2024",
        temperature: "2024",
        precipitation: "2024",
      },
    },
    {
      label: "Iowa",
      svg: "/svgs/states/Iowa.svg",
      value: "Iowa",
      type: "states",
      startDates: {
        threshold: "1900",
        temperature: "1895",
        precipitation: "1895",
      },
      endDates: {
        threshold: "2024",
        temperature: "2024",
        precipitation: "2024",
      },
    },
    {
      label: "Kansas",
      svg: "/svgs/states/Kansas.svg",
      value: "Kansas",
      type: "states",
      startDates: {
        threshold: "1900",
        temperature: "1895",
        precipitation: "1895",
      },
      endDates: {
        threshold: "2024",
        temperature: "2024",
        precipitation: "2024",
      },
    },
    {
      label: "Kentucky",
      svg: "/svgs/states/Kentucky.svg",
      value: "Kentucky",
      type: "states",
      startDates: {
        threshold: "1900",
        temperature: "1895",
        precipitation: "1895",
      },
      endDates: {
        threshold: "2024",
        temperature: "2024",
        precipitation: "2024",
      },
    },
    {
      label: "Louisiana",
      svg: "/svgs/states/Louisiana.svg",
      value: "Louisiana",
      type: "states",
      startDates: {
        threshold: "1900",
        temperature: "1895",
        precipitation: "1895",
      },
      endDates: {
        threshold: "2024",
        temperature: "2024",
        precipitation: "2024",
      },
    },
    {
      label: "Maine",
      svg: "/svgs/states/Maine.svg",
      value: "Maine",
      type: "states",
      startDates: {
        threshold: "1900",
        temperature: "1895",
        precipitation: "1895",
      },
      endDates: {
        threshold: "2024",
        temperature: "2024",
        precipitation: "2024",
      },
    },
    {
      label: "Maryland",
      svg: "/svgs/states/Maryland.svg",
      value: "Maryland",
      type: "states",
      startDates: {
        threshold: "1950",
        temperature: "1895",
        precipitation: "1895",
      },
      endDates: {
        threshold: "2024",
        temperature: "2024",
        precipitation: "2024",
      },
    },
    {
      label: "Massachusetts",
      svg: "/svgs/states/Massachusetts.svg",
      value: "Massachusetts",
      type: "states",
      startDates: {
        threshold: "1950",
        temperature: "1895",
        precipitation: "1895",
      },
      endDates: {
        threshold: "2024",
        temperature: "2024",
        precipitation: "2024",
      },
    },
    {
      label: "Michigan",
      svg: "/svgs/states/Michigan.svg",
      value: "Michigan",
      type: "states",
      startDates: {
        threshold: "1900",
        temperature: "1895",
        precipitation: "1895",
      },
      endDates: {
        threshold: "2024",
        temperature: "2024",
        precipitation: "2024",
      },
    },
    {
      label: "Minnesota",
      svg: "/svgs/states/Minnesota.svg",
      value: "Minnesota",
      type: "states",
      startDates: {
        threshold: "1900",
        temperature: "1895",
        precipitation: "1895",
      },
      endDates: {
        threshold: "2024",
        temperature: "2024",
        precipitation: "2024",
      },
    },
    {
      label: "Mississippi",
      svg: "/svgs/states/Mississippi.svg",
      value: "Mississippi",
      type: "states",
      startDates: {
        threshold: "1900",
        temperature: "1895",
        precipitation: "1895",
      },
      endDates: {
        threshold: "2024",
        temperature: "2024",
        precipitation: "2024",
      },
    },
    {
      label: "Missouri",
      svg: "/svgs/states/Missouri.svg",
      value: "Missouri",
      type: "states",
      startDates: {
        threshold: "1900",
        temperature: "1895",
        precipitation: "1895",
      },
      endDates: {
        threshold: "2024",
        temperature: "2024",
        precipitation: "2024",
      },
    },
    {
      label: "Montana",
      svg: "/svgs/states/Montana.svg",
      value: "Montana",
      type: "states",
      startDates: {
        threshold: "1900",
        temperature: "1895",
        precipitation: "1895",
      },
      endDates: {
        threshold: "2024",
        temperature: "2024",
        precipitation: "2024",
      },
    },
    {
      label: "Nebraska",
      svg: "/svgs/states/Nebraska.svg",
      value: "Nebraska",
      type: "states",
      startDates: {
        threshold: "1900",
        temperature: "1895",
        precipitation: "1895",
      },
      endDates: {
        threshold: "2024",
        temperature: "2024",
        precipitation: "2024",
      },
    },
    {
      label: "Nevada",
      svg: "/svgs/states/Nevada.svg",
      value: "Nevada",
      type: "states",
      startDates: {
        threshold: "1950",
        temperature: "1895",
        precipitation: "1895",
      },
      endDates: {
        threshold: "2024",
        temperature: "2024",
        precipitation: "2024",
      },
    },
    {
      label: "New Hampshire",
      svg: "/svgs/states/New_Hampshire.svg",
      value: "New_Hampshire",
      type: "states",
      startDates: {
        threshold: "1950",
        temperature: "1895",
        precipitation: "1895",
      },
      endDates: {
        threshold: "2024",
        temperature: "2024",
        precipitation: "2024",
      },
    },
    {
      label: "New Jersey",
      svg: "/svgs/states/New_Jersey.svg",
      value: "New_Jersey",
      type: "states",
      startDates: {
        threshold: "1900",
        temperature: "1895",
        precipitation: "1895",
      },
      endDates: {
        threshold: "2024",
        temperature: "2024",
        precipitation: "2024",
      },
    },
    {
      label: "New Mexico",
      svg: "/svgs/states/New_Mexico.svg",
      value: "New_Mexico",
      type: "states",
      startDates: {
        threshold: "1900",
        temperature: "1895",
        precipitation: "1895",
      },
      endDates: {
        threshold: "2024",
        temperature: "2024",
        precipitation: "2024",
      },
    },
    {
      label: "New York",
      svg: "/svgs/states/New_York.svg",
      value: "New_York",
      type: "states",
      startDates: {
        threshold: "1900",
        temperature: "1895",
        precipitation: "1895",
      },
      endDates: {
        threshold: "2024",
        temperature: "2024",
        precipitation: "2024",
      },
    },
    {
      label: "North Carolina",
      svg: "/svgs/states/North_Carolina.svg",
      value: "North_Carolina",
      type: "states",
      startDates: {
        threshold: "1900",
        temperature: "1895",
        precipitation: "1895",
      },
      endDates: {
        threshold: "2024",
        temperature: "2024",
        precipitation: "2024",
      },
    },
    {
      label: "North Dakota",
      svg: "/svgs/states/North_Dakota.svg",
      value: "North_Dakota",
      type: "states",
      startDates: {
        threshold: "1900",
        temperature: "1895",
        precipitation: "1895",
      },
      endDates: {
        threshold: "2024",
        temperature: "2024",
        precipitation: "2024",
      },
    },
    {
      label: "Ohio",
      svg: "/svgs/states/Ohio.svg",
      value: "Ohio",
      type: "states",
      startDates: {
        threshold: "1900",
        temperature: "1895",
        precipitation: "1895",
      },
      endDates: {
        threshold: "2024",
        temperature: "2024",
        precipitation: "2024",
      },
    },
    {
      label: "Oklahoma",
      svg: "/svgs/states/Oklahoma.svg",
      value: "Oklahoma",
      type: "states",
      startDates: {
        threshold: "1900",
        temperature: "1895",
        precipitation: "1895",
      },
      endDates: {
        threshold: "2024",
        temperature: "2024",
        precipitation: "2024",
      },
    },
    {
      label: "Oregon",
      svg: "/svgs/states/Oregon.svg",
      value: "Oregon",
      type: "states",
      startDates: {
        threshold: "1900",
        temperature: "1895",
        precipitation: "1895",
      },
      endDates: {
        threshold: "2024",
        temperature: "2024",
        precipitation: "2024",
      },
    },
    {
      label: "Pennsylvania",
      svg: "/svgs/states/Pennsylvania.svg",
      value: "Pennsylvania",
      type: "states",
      startDates: {
        threshold: "1900",
        temperature: "1895",
        precipitation: "1895",
      },
      endDates: {
        threshold: "2024",
        temperature: "2024",
        precipitation: "2024",
      },
    },
    {
      label: "Rhode Island",
      svg: "/svgs/states/Rhode_Island.svg",
      value: "Rhode_Island",
      type: "states",
      startDates: {
        threshold: "1950",
        temperature: "1895",
        precipitation: "1895",
      },
      endDates: {
        threshold: "2024",
        temperature: "2024",
        precipitation: "2024",
      },
    },
    {
      label: "South Carolina",
      svg: "/svgs/states/South_Carolina.svg",
      value: "South_Carolina",
      type: "states",
      startDates: {
        threshold: "1900",
        temperature: "1895",
        precipitation: "1895",
      },
      endDates: {
        threshold: "2024",
        temperature: "2024",
        precipitation: "2024",
      },
    },
    {
      label: "South Dakota",
      svg: "/svgs/states/South_Dakota.svg",
      value: "South_Dakota",
      type: "states",
      startDates: {
        threshold: "1900",
        temperature: "1895",
        precipitation: "1895",
      },
      endDates: {
        threshold: "2024",
        temperature: "2024",
        precipitation: "2024",
      },
    },
    {
      label: "Tennessee",
      svg: "/svgs/states/Tennessee.svg",
      value: "Tennessee",
      type: "states",
      startDates: {
        threshold: "1900",
        temperature: "1895",
        precipitation: "1895",
      },
      endDates: {
        threshold: "2024",
        temperature: "2024",
        precipitation: "2024",
      },
    },
    {
      label: "Texas",
      svg: "/svgs/states/Texas.svg",
      value: "Texas",
      type: "states",
      startDates: {
        threshold: "1900",
        temperature: "1895",
        precipitation: "1895",
      },
      endDates: {
        threshold: "2024",
        temperature: "2024",
        precipitation: "2024",
      },
    },
    {
      label: "Utah",
      svg: "/svgs/states/Utah.svg",
      value: "Utah",
      type: "states",
      startDates: {
        threshold: "1900",
        temperature: "1895",
        precipitation: "1895",
      },
      endDates: {
        threshold: "2024",
        temperature: "2024",
        precipitation: "2024",
      },
    },
    {
      label: "Vermont",
      svg: "/svgs/states/Vermont.svg",
      value: "Vermont",
      type: "states",
      startDates: {
        threshold: "1950",
        temperature: "1895",
        precipitation: "1895",
      },
      endDates: {
        threshold: "2024",
        temperature: "2024",
        precipitation: "2024",
      },
    },
    {
      label: "Virginia",
      svg: "/svgs/states/Virginia.svg",
      value: "Virginia",
      type: "states",
      startDates: {
        threshold: "1900",
        temperature: "1895",
        precipitation: "1895",
      },
      endDates: {
        threshold: "2024",
        temperature: "2024",
        precipitation: "2024",
      },
    },
    {
      label: "Washington",
      svg: "/svgs/states/Washington.svg",
      value: "Washington",
      type: "states",
      startDates: {
        threshold: "1900",
        temperature: "1895",
        precipitation: "1895",
      },
      endDates: {
        threshold: "2024",
        temperature: "2024",
        precipitation: "2024",
      },
    },
    {
      label: "West Virginia",
      svg: "/svgs/states/West_Virginia.svg",
      value: "West_Virginia",
      type: "states",
      startDates: {
        threshold: "1900",
        temperature: "1895",
        precipitation: "1895",
      },
      endDates: {
        threshold: "2024",
        temperature: "2024",
        precipitation: "2024",
      },
    },
    {
      label: "Wisconsin",
      svg: "/svgs/states/Wisconsin.svg",
      value: "Wisconsin",
      type: "states",
      startDates: {
        threshold: "1900",
        temperature: "1895",
        precipitation: "1895",
      },
      endDates: {
        threshold: "2024",
        temperature: "2024",
        precipitation: "2024",
      },
    },
    {
      label: "Wyoming",
      svg: "/svgs/states/Wyoming.svg",
      value: "Wyoming",
      type: "states",
      startDates: {
        threshold: "1950",
        temperature: "1895",
        precipitation: "1895",
      },
      endDates: {
        threshold: "2024",
        temperature: "2024",
        precipitation: "2024",
      },
    },
  ],
  // Regions options for MegaMenu.jsx
  regionsOptions: [
    {
      label: "Alaska",
      svg: "/svgs/regions/alaska.svg",
      description: "Alaska",
      value: "alaska_region",
      type: "regions",
      startDates: {
        threshold: "1930",
        temperature: "1900",
        precipitation: "1900",
      },
      endDates: {
        threshold: "2024",
        temperature: "2024",
        precipitation: "2024",
      },
    },
    {
      label: "Hawai'i and US-Affiliated Pacific Islands",
      svg: "/svgs/regions/hawaii.svg",
      description: "Hawai'i",
      value: "hawaii",
      type: "regions",
    },
    {
      label: "Northeast",
      svg: "/svgs/regions/northeast.svg",
      description:
        "Connecticut, Delaware, Maine, Maryland, Massachusetts, New Hampshire, New Jersey, New York, Pennsylvania, Rhode Island, & Vermont",
      value: "northeast",
      type: "regions",
      startDates: {
        threshold: "1900",
        temperature: "1895",
        precipitation: "1895",
      },
      endDates: {
        threshold: "2024",
        temperature: "2024",
        precipitation: "2024",
      },
    },
    {
      label: "Northern Rockies and Plains",
      svg: "/svgs/regions/northern_rockies_plains.svg",
      description: "Montana, Nebraska, North Dakota, South Dakota, & Wyoming",
      value: "northern_rockies_plains",
      type: "regions",
      startDates: {
        threshold: "1900",
        temperature: "1895",
        precipitation: "1895",
      },
      endDates: {
        threshold: "2024",
        temperature: "2024",
        precipitation: "2024",
      },
    },
    {
      label: "Northwest",
      svg: "/svgs/regions/northwest.svg",
      description: "Idaho, Oregon, & Washington",
      value: "northwest",
      type: "regions",
      startDates: {
        threshold: "1900",
        temperature: "1895",
        precipitation: "1895",
      },
      endDates: {
        threshold: "2024",
        temperature: "2024",
        precipitation: "2024",
      },
    },
    {
      label: "Ohio Valley",
      svg: "/svgs/regions/ohio_valley.svg",
      description:
        "Illinois, Indiana, Kentucky, Missouri, Ohio, Tennessee, & West Virginia",
      value: "ohio_valley",
      type: "regions",
      startDates: {
        threshold: "1900",
        temperature: "1895",
        precipitation: "1895",
      },
      endDates: {
        threshold: "2024",
        temperature: "2024",
        precipitation: "2024",
      },
    },
    {
      label: "South",
      svg: "/svgs/regions/south.svg",
      description:
        "Alabama, Arkansas, Louisiana, Mississippi, Oklahoma, & Texas",
      value: "south",
      type: "regions",
      startDates: {
        threshold: "1900",
        temperature: "1895",
        precipitation: "1895",
      },
      endDates: {
        threshold: "2024",
        temperature: "2024",
        precipitation: "2024",
      },
    },
    {
      label: "Southeast",
      svg: "/svgs/regions/southeast.svg",
      description:
        "Florida, Georgia, North Carolina, South Carolina, & Virginia",
      value: "southeast",
      type: "regions",
      startDates: {
        threshold: "1900",
        temperature: "1895",
        precipitation: "1895",
      },
      endDates: {
        threshold: "2024",
        temperature: "2024",
        precipitation: "2024",
      },
    },
    {
      label: "Southwest",
      svg: "/svgs/regions/southwest.svg",
      description: "Arizona, Colorado, New Mexico, & Utah",
      value: "southwest",
      type: "regions",
      startDates: {
        threshold: "1900",
        temperature: "1895",
        precipitation: "1895",
      },
      endDates: {
        threshold: "2024",
        temperature: "2024",
        precipitation: "2024",
      },
    },
    {
      label: "Upper Midwest",
      svg: "/svgs/regions/upper_midwest.svg",
      description: "Iowa, Michigan, Minnesota, & Wisconsin",
      value: "upper_midwest",
      type: "regions",
      startDates: {
        threshold: "1900",
        temperature: "1895",
        precipitation: "1895",
      },
      endDates: {
        threshold: "2024",
        temperature: "2024",
        precipitation: "2024",
      },
    },
    {
      label: "US Caribbean",
      svg: "/svgs/regions/us_caribbean.svg",
      description: "Puerto Rico & U.S. Virgin Islands",
      value: "us_caribbean",
      type: "regions",
    },
    {
      label: "West",
      svg: "/svgs/regions/west.svg",
      description: "California, Nevada",
      value: "west",
      type: "regions",
      startDates: {
        threshold: "1930",
        temperature: "1895",
        precipitation: "1895",
      },
      endDates: {
        threshold: "2024",
        temperature: "2024",
        precipitation: "2024",
      },
    },
    {
      label: "Contiguous United States",
      svg: "/svgs/contiguous_usa.svg",
      value: "contiguous",
      type: "CONUS",
      startDates: {
        threshold: "1900",
        temperature: "1895",
        precipitation: "1895",
      },
      endDates: {
        threshold: "2024",
        temperature: "2024",
        precipitation: "2024",
      },
    },
  ],
};

export default config;
