const SandboxClimateVariableValueNamesHumanReadable = () => [
  {
    value: "prcp_1inch",
    pullDownText: "Days with Precipitation Greater than 1 inch",
    chartTitle: "Number of Days with Precipitation Greater than 1 inch",
    season: "ann",
  },
  {
    value: "prcp_2inch",
    pullDownText: "Days with Precipitation Greater than 2 inches",
    chartTitle: "Number of Days with Precipitation Greater than 2 inches",
    season: "ann",
  },
  {
    value: "prcp_3inch",
    pullDownText: "Days with Precipitation Greater than 3 inches",
    chartTitle: "Number of Days with Precipitation Greater than 3 inches",
    season: "ann",
  },
  {
    value: "prcp_4inch",
    pullDownText: "Days with Precipitation Greater than 4 inches",
    chartTitle: "Number of Days with Precipitation Greater than 4 inches",
    season: "ann",
  },
  {
    value: "tmax_0F",
    pullDownText: "Days with Maximum Temperature Below 0°F",
    chartTitle: "Number of Days with Maximum Temperature Below 0°F",
    season: "ann",
  },
  {
    value: "tmax_32F",
    pullDownText: "Days with Maximum Temperature Below 32°F",
    chartTitle: "Number of Days with Maximum Temperature Below 32°F",
    season: "ann",
  },
  {
    value: "tmax_90F",
    pullDownText: "Days with Maximum Temperature Above 90°F",
    chartTitle: "Number of Days with Maximum Temperature Above 90°F",
    season: "ann",
  },
  {
    value: "tmax_95F",
    pullDownText: "Days with Maximum Temperature Above 95°F",
    chartTitle: "Number of Days with Maximum Temperature Above 95°F",
    season: "ann",
  },
  {
    value: "tmax_100F",
    pullDownText: "Days with Maximum Temperature Above 100°F",
    chartTitle: "Number of Days with Maximum Temperature Above 100°F",
    season: "ann",
  },
  {
    value: "tmin_0F",
    pullDownText: "Days with Minimum Temperature Below 0°F",
    chartTitle: "Number of Days with Minimum Temperature Below 0°F",
    season: "ann",
  },
  {
    value: "tmin_32F",
    pullDownText: "Days with Minimum Temperature Below 32°F",
    chartTitle: "Number of Days with Minimum Temperature Below 32°F",
    season: "ann",
  },
  {
    value: "tmin_70F",
    pullDownText: "Days with Minimum Temperature Above 70°F",
    chartTitle: "Number of Days with Minimum Temperature Above 70°F",
    season: "ann",
  },
  {
    value: "tmin_75F",
    pullDownText: "Days with Minimum Temperature Above 75°",
    chartTitle: "Number of Days with Minimum Temperature Above 75°",
    season: "ann",
  },
  {
    value: "tmin_80F",
    pullDownText: "Days with Minimum Temperature Above 80°F",
    chartTitle: "Number of Days with Minimum Temperature Above 80°F",
    season: "ann",
  },
  {
    value: "prcp_ann",
    pullDownText: "Total Precipitation",
    chartTitle: "Annual (Jan—Dec) Total Precipitation",
    season: "ann",
  },
  {
    value: "tmean_ann",
    pullDownText: "Average Temperature",
    chartTitle: "Annual (Jan—Dec) Average Temperature",
    season: "ann",
  },
  {
    value: "tmin_ann",
    pullDownText: "Average Minimum Temperature",
    chartTitle: "Annual (Jan—Dec) Average Minimum Temperature",
    season: "ann",
  },
  {
    value: "tmax_ann",
    pullDownText: "Average Maximum Temperature",
    chartTitle: "Annual (Jan—Dec) Average Maximum Temperature",
    season: "ann",
  },
  {
    value: "prcp_djf",
    pullDownText: "Total Precipitation",
    chartTitle: "Winter (Dec, Jan, Feb) Total Precipitation",
    season: "djf",
  },
  {
    value: "tmean_djf",
    pullDownText: "Average Temperature",
    chartTitle: "Winter (Dec, Jan, Feb) Average Temperature",
    season: "djf",
  },
  {
    value: "tmin_djf",
    pullDownText: "Average Minimum Temperature",
    chartTitle: "Winter (Dec, Jan, Feb) Average Minimum Temperature",
    season: "djf",
  },
  {
    value: "tmax_djf",
    pullDownText: "Average Maximum Temperature",
    chartTitle: "Winter (Dec, Jan, Feb) Average Maximum Temperature",
    season: "djf",
  },
  {
    value: "prcp_mam",
    pullDownText: "Total Precipitation",
    chartTitle: "Spring (Mar, Apr, May) Total Precipitation",
    season: "mam",
  },
  {
    value: "tmean_mam",
    pullDownText: "Average Temperature",
    chartTitle: "Spring (Mar, Apr, May) Average Temperature",
    season: "mam",
  },
  {
    value: "tmin_mam",
    pullDownText: "Average Minimum Temperature",
    chartTitle: "Spring (Mar, Apr, May) Average Minimum Temperature",
    season: "mam",
  },
  {
    value: "tmax_mam",
    pullDownText: "Average Maximum Temperature",
    chartTitle: "Spring (Mar, Apr, May) Average Maximum Temperature",
    season: "mam",
  },
  {
    value: "prcp_jja",
    pullDownText: "Total Precipitation",
    chartTitle: "Summer (Jun, Jul, Aug) Total Precipitation",
    season: "jja",
  },
  {
    value: "tmean_jja",
    pullDownText: "Average Temperature",
    chartTitle: "Summer (Jun, Jul, Aug) Average Temperature",
    season: "jja",
  },
  {
    value: "tmin_jja",
    pullDownText: "Average Minimum Temperature",
    chartTitle: "Summer (Jun, Jul, Aug) Average Minimum Temperature",
    season: "jja",
  },
  {
    value: "tmax_jja",
    pullDownText: "Average Maximum Temperature",
    chartTitle: "Summer (Jun, Jul, Aug) Average Maximum Temperature",
    season: "jja",
  },
  {
    value: "prcp_son",
    pullDownText: "Total Precipitation",
    chartTitle: "Fall (Sep, Oct, Nov) Total Precipitation",
    season: "son",
  },
  {
    value: "tmean_son",
    pullDownText: "Average Temperature",
    chartTitle: "Fall (Sep, Oct, Nov) Average Temperature",
    season: "son",
  },
  {
    value: "tmin_son",
    pullDownText: "Average Minimum Temperature",
    chartTitle: "Fall (Sep, Oct, Nov) Average Minimum Temperature",
    season: "son",
  },
  {
    value: "tmax_son",
    pullDownText: "Average Maximum Temperature",
    chartTitle: "Fall (Sep, Oct, Nov) Average Maximum Temperature",
    season: "son",
  },
  {
    value: "cddc",
    pullDownText: "Cooling Degree Days",
    chartTitle: "Annual (Jan—Dec) Cooling Degree Days",
    season: "ann",
  },
  {
    value: "cddc",
    pullDownText: "Cooling Degree Days",
    chartTitle: "Winter (Dec, Jan, Feb) Cooling Degree Days",
    season: "djf",
  },
  {
    value: "cddc",
    pullDownText: "Cooling Degree Days",
    chartTitle: "Spring (Mar, Apr, May) Cooling Degree Days",
    season: "mam",
  },
  {
    value: "cddc",
    pullDownText: "Cooling Degree Days",
    chartTitle: "Summer (Jun, Jul, Aug) Cooling Degree Days",
    season: "jja",
  },
  {
    value: "cddc",
    pullDownText: "Cooling Degree Days",
    chartTitle: "Fall (Sep, Oct, Nov) Cooling Degree Days",
    season: "son",
  },

  {
    value: "hddc",
    pullDownText: "Heating Degree Days",
    chartTitle: "Annual (Jan—Dec) Heating Degree Days",
    season: "ann",
  },
  {
    value: "hddc",
    pullDownText: "Heating Degree Days",
    chartTitle: "Winter (Dec, Jan, Feb) Heating Degree Days",
    season: "djf",
  },
  {
    value: "hddc",
    pullDownText: "Heating Degree Days",
    chartTitle: "Spring (Mar, Apr, May) Heating Degree Days",
    season: "mam",
  },
  {
    value: "hddc",
    pullDownText: "Heating Degree Days",
    chartTitle: "Summer (Jun, Jul, Aug) Heating Degree Days",
    season: "jja",
  },
  {
    value: "hddc",
    pullDownText: "Heating Degree Days",
    chartTitle: "Fall (Sep, Oct, Nov) Heating Degree Days",
    season: "son",
  },
];
export default SandboxClimateVariableValueNamesHumanReadable;
